version: '3.4'

services:
  redis-node1:
    image: redis:7.0
    restart: always
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf]
    volumes:
      - ./redis-cluster.conf:/etc/redis/redis-cluster.conf

  redis-node2:
    image: redis:7.0
    restart: always
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf]
    volumes:
      - ./redis-cluster.conf:/etc/redis/redis-cluster.conf

  redis-node3:
    image: redis:7.0
    restart: always
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf]
    volumes:
      - ./redis-cluster.conf:/etc/redis/redis-cluster.conf

  redis-node4:
    image: redis:7.0
    restart: always
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf]
    volumes:
      - ./redis-cluster.conf:/etc/redis/redis-cluster.conf

  redis-node5:
    image: redis:7.0
    restart: always
    entrypoint: [redis-server, /etc/redis/redis-cluster.conf]
    volumes:
      - ./redis-cluster.conf:/etc/redis/redis-cluster.conf

  redis-node6:
    image: redis:7.0
    restart: always
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli -a jo123 --cluster create manual_redis-node2_1:6379 manual_redis-node1_1:6379 manual_redis-node3_1:6379 manual_redis-node4_1:6379 manual_redis-node5_1:6379 manual_redis-node6_1:6379 --cluster-replicas 1 | redis-server /etc/redis/redis-cluster.conf']

    volumes:
      - ./redis-cluster.conf:/etc/redis/redis-cluster.conf
